version: '3'

networks:
  laravel8:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8081:80" # binds local port 8081 to container port 80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel8
  
  mysql:
    image: mariadb:10.3.17
    container_name: mysql
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=mysql_dev
      - MYSQL_PASSWORD=mysql_dev
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - laravel8
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=64M
    
  php: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel8
  
  # composer: 
  #   container_name: composer
  #   image: composer:latest
  #   command: ["composer", "install"]
  #   depends_on:
  #     - php80
  #   volumes:
  #     - ./src/laravel8:/app
  #   restart: always
  #   networks:
  #     - laravel8
